# Generated by Django 3.2.20 on 2023-07-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('discount', models.FloatField(default=0, verbose_name='Descuento')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad de veces que se puede usar')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_buyer', models.CharField(max_length=70, verbose_name='Nombre del comprador')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes de compra',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('price', models.FloatField(default=0, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Mensaje de bienvenida')),
                ('temperature_min', models.IntegerField(verbose_name='Temperatura mínima (mínima 0°)')),
                ('temperature_max', models.IntegerField(verbose_name='Temperatura máxima (máxima 50°)')),
            ],
            options={
                'verbose_name': 'Mensaje de bienvenida',
                'verbose_name_plural': 'Mensajes de bienvenida',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heladeriafrozen.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heladeriafrozen.product')),
            ],
            options={
                'verbose_name': 'Orden de producto',
                'verbose_name_plural': 'Ordenes de producto',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='heladeriafrozen.Product'),
        ),
    ]
