# Generated by Django 3.2.20 on 2023-07-04 23:35

from django.db import migrations, models
import heladeriafrozen.models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeriafrozen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=heladeriafrozen.models.custom_upload_to, verbose_name='Imagen de producto'),
        ),
    ]
